### ISSUE TITLE
How is the 24H APR value calculated?

### ISSUE THREAD

**Issue by dustiarmor** [raydium-io/raydium-clmm#82]
If I get APR 24H = 204.42% (Trade fees 202.78% , RAY 1.64%) for SOL-USDC pair in V3 concentrated pools.
Current Liquidity= $5102803; Vol 24H = $56697714;  Fees 24H = $28349
so..How to calculate APR 24H?

**Comment by RainRaydium** [comment]
The evaluation calculation of clmm apr is different from that of amm because it depends on the pool price and market making range. We use several different algorithms. 
You can refer to this link: [https://docs.raydium.io/raydium/liquidity-providers/providing-concentrated-liquidity-clmm/estimated-apr-calculations](url)
