### ISSUE TITLE
so outdated it conflicts with everything else

### ISSUE THREAD

**Issue by gladwinput** [raydium-io/raydium-clmm#91]
Hello,

This package relies on such an old version of solana it breaks every single package it interacts with including some of your own pacakges. raydium-contract-instructions, amongst others. Can you consider updating it to latest? It is shockingly behind in versions

**Comment by RainRaydium** [comment]
Because upgrading the solana version requires upgrading the anchor version to 0.30.1, but after trying to upgrade, a `Stack offset` error would be thrown. You can refer to [https://github.com/coral-xyz/anchor/pull/2939](url).
And this error will be solved in the next anchor version, so after the anchor is upgraded, we will perform a corresponding version update.
Thanks!
